services:
  md-editor:
    image: ghcr.io/mazaiguo/mdeditor:latest
    container_name: md-editor
    restart: unless-stopped
    ports:
      - "5080:5080"
    volumes:
      - ./data/images:/app/dist/images
    environment:
      - PORT=5080
